name: Build TestKST

on: 
  push:
    paths:
      - 'src/*'

jobs:
  build-TestKST:
    name: Build TestKST

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build TestKST
      run: dotnet build --configuration Release src/TestKST
